{
  "openapi": "3.0.0",
  "info": {
    "title": "Desafio FullStack, M6 Sprint 2 - Wigny Oliveira",
    "description": "Para quem desejar testar a aplicação: Lembre-se de criar um arquivo .env com as configurações que possuí no .env.example. Criar também um banco de dados em sua maquina",
    "contact": {
      "name": "Wigny Oliveira",
      "url": "https://www.linkedin.com/in/wigny-oliveira/",
      "email": "wigny_36@hotmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": ["http"],
  "paths": {
    "/login": {
      "post": {
        "summary": "Entrar na Conta",
        "description": "Essa rota é Resposável para disponibilizar o Token para o Cliente",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "value": {
                  "email": "string",
                  "password": "string"
                }
              },
              "examples": {
                "success": {
                  "value": {
                    "email": "wigny_36@hotmail.com",
                    "password": "123456@Ab"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "success": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Invalid credentials"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/clients": {
      "post": {
        "summary": "Cadastro de Cliente",
        "description": "Essa rota cria um cliente",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "examples": {
                "client": {
                  "value": {
                    "firstName": "Wigny",
                    "lastName": "Oliveira",
                    "password": "123456@Ab",
                    "email": "wigny@kenzie.com",
                    "telephone": "11974146527"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ClientCreated"
                }
              }
            }
          },
          "409": {
            "description": "Email already exists"
          }
        }
      },
      "get": {
        "summary": "Listagem de Cliente",
        "description": "Essa rota mostra todos os clientes",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/ClientCreated"
                }
              }
            }
          }
        }
      }
    },
    "/clients/{idClient}": {
      "get": {
        "summary": "Listagem de Cliente Pelo ID",
        "description": "Essa rota mostra um cliente",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ClientCreated"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Client not found."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "invalid input syntax for type uuid: ..."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Atualização de um Cliente",
        "description": "Essa rota atualiza o cliente que foi passado pela url",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ClientCreated"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Client not found."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deleção de um Cliente",
        "description": "Essa rota Deleta um Cliente que foi passado pela url",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Client not found."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts": {
      "post": {
        "summary": "Cadastro de um Contato",
        "description": "Precisa estar logado para ter acesso, para que possa capturar o Cliente com base no token passado",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contact"
              },
              "examples": {
                "Contact": {
                  "value": {
                    "name": "Paulo - Instrutor",
                    "telephone": "11987654321"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ContactCreated"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{idContact}": {
      "get": {
        "summary": "Listagem do contato Pelo ID",
        "description": "Essa Rota Mostra o Contato que foi passado pelo URL, Precisa estar logado para ter acesso",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ContactCreated"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Atualização de um Contato",
        "description": "Essa rota atualiza o contato que foi Passado pela URL, Precisa estar logado para ter acesso",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ContactCreated"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deleção de um Contato",
        "description": "Essa rota Deleta um Contato que foi Passado pela URL, Precisa estar logado para ter acesso",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Missin bearer token"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Client": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          }
        }
      },
      "ClientCreated": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "deletedAt": {
            "type": "string"
          }
        }
      },
      "ContactCreated": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "client": {
            "$ref": "#/components/schemas/ClientCreated"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
